export default (
  '<div class="cropper-container" touch-action="none">'
    + '<div class="cropper-canvas"></div>'
    + '<div class="cropper-drag-box"></div>'
    + '<div class="cropper-crop-box">'
      + '<div class="cropper-view-box"></div>'
      + '<div class="cropper-dashed dashed-h"></div>'
      + '<div class="cropper-dashed dashed-v"></div>'
      + '<div class="cropper-center"></div>'
      + '<div class="cropper-face"></div>'
      + '<div class="cropper-line line-e" data-cropper-action="e"></div>'
      + '<div class="cropper-line line-n" data-cropper-action="n"></div>'
      + '<div class="cropper-line line-w" data-cropper-action="w"></div>'
      + '<div class="cropper-line line-s" data-cropper-action="s"></div>'
      + '<div class="cropper-point point-e" data-cropper-action="e"></div>'
      + '<div class="cropper-point point-n" data-cropper-action="n"></div>'
      + '<div class="cropper-point point-w" data-cropper-action="w"></div>'
      + '<div class="cropper-point point-s" data-cropper-action="s"></div>'
      + '<div class="cropper-point point-ne" data-cropper-action="ne"></div>'
      + '<div class="cropper-point point-nw" data-cropper-action="nw"></div>'
      + '<div class="cropper-point point-sw" data-cropper-action="sw"></div>'
      + '<div class="cropper-point point-se" data-cropper-action="se"></div>'
    + '</div>'
  + '</div>'
);
