export default (
  '<cropper-canvas background>'
    + '<cropper-image></cropper-image>'
    + '<cropper-handle action="select" theme-color="rgba(0, 0, 0, 0.65)"></cropper-handle>'
    + '<cropper-selection auto-select auto-select-area="0.5">'
      + '<cropper-grid role="grid"></cropper-grid>'
      + '<cropper-crosshair></cropper-crosshair>'
      + '<cropper-handle action="move" theme-color="rgba(255, 255, 255, 0.35)"></cropper-handle>'
      + '<cropper-handle action="n-resize"></cropper-handle>'
      + '<cropper-handle action="e-resize"></cropper-handle>'
      + '<cropper-handle action="s-resize"></cropper-handle>'
      + '<cropper-handle action="w-resize"></cropper-handle>'
      + '<cropper-handle action="ne-resize"></cropper-handle>'
      + '<cropper-handle action="nw-resize"></cropper-handle>'
      + '<cropper-handle action="se-resize"></cropper-handle>'
      + '<cropper-handle action="sw-resize"></cropper-handle>'
    + '</cropper-selection>'
  + '</cropper-canvas>'
);
