name: Deploy

on:
  push:
    tags:
      - v1.*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cp -r docs .temp
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          clean: false
      - run: rm -rf v1
      - run: mkdir -p v1
      - run: cp -rf .temp/* v1
      - run: rm -r .temp
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
      - run: git add v1
      - run: git commit --message "${{ github.ref_name }}"
      - run: git push
